import './globals.css'
import Link from 'next/link'

const links = [{
  label: 'Parker',
  route: '/parker'
},{
label: 'Driver',
route: '/driver'
}]

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
    <head><script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCziTRCAS24xZAsN9cjqhI4w_oUE8velIw&libraries=places&callback=Function.prototype" async></script>
    </head>
      <body>
      <header>
          <nav>
           <ul>
          {links.map(({label,route}) => (
          <li key={route}>
            <Link href={route}>{label}</Link>
         </li>
          ))}
         </ul>
    </nav>
</header>
      {children}</body>
    </html>
  )
}
